services:
  # 1. The Backend
  - type: web
    name: lightning-store
    runtime: python
    plan: free
    buildCommand: pip install .
    startCommand: agl store --host 0.0.0.0 --port $PORT

  # 2. The Dashboard
  - type: web
    name: lightning-dashboard
    runtime: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    # This rule fixes the "Blank Page on Refresh" issue
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
