services:
  - type: web
    name: lightning-store
    runtime: python
    plan: free
    buildCommand: pip install .
    startCommand: agl store --host 0.0.0.0 --port $PORT

  - type: web
    name: lightning-dashboard
    runtime: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
